# Generated by Django 4.2.2 on 2023-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaa', '0002_program_close_program_gender_program_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='close',
            field=models.FloatField(default=99999),
        ),
        migrations.AlterField(
            model_name='program',
            name='open',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='program',
            name='roundd',
            field=models.FloatField(default=6),
        ),
        migrations.AlterField(
            model_name='program',
            name='year',
            field=models.FloatField(default=2020),
        ),
    ]
