# Generated by Django 4.2.2 on 2023-06-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josaa', '0003_alter_program_close_alter_program_open_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='program',
            new_name='programm',
        ),
    ]
