# Generated by Django 4.2.2 on 2023-06-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josaa', '0004_rename_program_programm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programm',
            name='roundd',
        ),
    ]
