# Generated by Django 4.2.2 on 2023-06-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaa', '0005_remove_programm_roundd'),
    ]

    operations = [
        migrations.AddField(
            model_name='programm',
            name='roundd',
            field=models.IntegerField(default=1),
        ),
    ]
